import { PRODUCT_STATUS } from "../lib/product-status";

export const allProducts = [
  {
    name: "WhoBuildThis",
    slug: "whobuildthis",
    tagline: "Showcase the creators behind products",
    description:
      "A platform where makers can showcase their products and get discovered.",
    webURL: "https://whobuildthis.com",
    webImage: "https://picsum.photos/seed/whobuildthis/800/600",
    tags: ["startup", "saas", "showcase"],
    voteCount: 42,
    status: PRODUCT_STATUS.APPROVED,
    submittedBy: "Fasil",
    userId: "user_2aBcX123Fake",
    organizationId: null,
    approvedAt: new Date(),
  },
  {
    name: "DevShelf",
    slug: "devshelf",
    tagline: "Save and share developer tools",
    description:
      "A curated shelf of tools, libraries, and resources for developers.",
    webURL: "https://devshelf.dev",
    webImage: "https://picsum.photos/seed/devshelf/800/600",
    tags: ["developer", "tools", "productivity"],
    voteCount: 12,
    status: PRODUCT_STATUS.PENDING,
    submittedBy: "Alex",
    userId: "user_7XyZFake",
    organizationId: null,
    approvedAt: null,
  },
  {
    name: "UIForge",
    slug: "uiforge",
    tagline: "Build modern UI faster",
    description:
      "A collection of production-ready UI components for modern web apps.",
    webURL: "https://uiforge.dev",
    webImage: "https://picsum.photos/seed/uiforge/800/600",
    tags: ["ui", "design", "components"],
    voteCount: 58,
    status: PRODUCT_STATUS.APPROVED,
    submittedBy: "Rahul",
    userId: "user_uiForge123",
    organizationId: null,
    approvedAt: new Date(),
  },
  {
    name: "APIWatch",
    slug: "apiwatch",
    tagline: "Monitor APIs without hassle",
    description:
      "Real-time API monitoring, uptime tracking, and performance alerts.",
    webURL: "https://apiwatch.io",
    webImage: "https://picsum.photos/seed/apiwatch/800/600",
    tags: ["api", "monitoring", "saas"],
    voteCount: 31,
    status: PRODUCT_STATUS.APPROVED,
    submittedBy: "Neha",
    userId: "user_apiWatchX",
    organizationId: null,
    approvedAt: new Date(),
  },
  {
    name: "CodeNotes",
    slug: "codenotes",
    tagline: "Write notes like you write code",
    description:
      "Markdown-based note taking app designed for developers.",
    webURL: "https://codenotes.app",
    webImage: "https://picsum.photos/seed/codenotes/800/600",
    tags: ["notes", "developer", "productivity"],
    voteCount: 9,
    status: PRODUCT_STATUS.PENDING,
    submittedBy: "Aisha",
    userId: "user_codeNotes",
    organizationId: null,
    approvedAt: null,
  },
  {
    name: "LaunchTrack",
    slug: "launchtrack",
    tagline: "Track your product launches",
    description:
      "Plan, schedule, and track product launches in one place.",
    webURL: "https://launchtrack.co",
    webImage: "https://picsum.photos/seed/launchtrack/800/600",
    tags: ["launch", "marketing", "startup"],
    voteCount: 76,
    status: PRODUCT_STATUS.APPROVED,
    submittedBy: "Daniel",
    userId: "user_launchTrack",
    organizationId: null,
    approvedAt: new Date(),
  },
  {
    name: "BugZero",
    slug: "bugzero",
    tagline: "Ship code with confidence",
    description:
      "A lightweight bug tracking tool for small development teams.",
    webURL: "https://bugzero.dev",
    webImage: "https://picsum.photos/seed/bugzero/800/600",
    tags: ["bugs", "testing", "saas"],
    voteCount: 15,
    status: PRODUCT_STATUS.PENDING,
    submittedBy: "Karthik",
    userId: "user_bugZero",
    organizationId: null,
    approvedAt: null,
  },
  {
    name: "PromptBox",
    slug: "promptbox",
    tagline: "Manage and reuse AI prompts",
    description:
      "Save, organize, and share prompts for ChatGPT and other AI tools.",
    webURL: "https://promptbox.ai",
    webImage: "https://picsum.photos/seed/promptbox/800/600",
    tags: ["ai", "productivity", "tools"],
    voteCount: 64,
    status: PRODUCT_STATUS.APPROVED,
    submittedBy: "Sanjay",
    userId: "user_promptBox",
    organizationId: null,
    approvedAt: new Date(),
  },
  {
    name: "TaskFlow",
    slug: "taskflow",
    tagline: "Simple task management for teams",
    description:
      "A minimal task manager designed for fast-moving teams.",
    webURL: "https://taskflow.app",
    webImage: "https://picsum.photos/seed/taskflow/800/600",
    tags: ["tasks", "teams", "productivity"],
    voteCount: 22,
    status: PRODUCT_STATUS.REJECTED,
    submittedBy: "Mohit",
    userId: "user_taskFlow",
    organizationId: null,
    approvedAt: null,
  },
  {
    name: "SnippetHub",
    slug: "snippethub",
    tagline: "Store and share code snippets",
    description:
      "A cloud-based snippet manager for developers and teams.",
    webURL: "https://snippethub.dev",
    webImage: "https://picsum.photos/seed/snippethub/800/600",
    tags: ["code", "developer", "tools"],
    voteCount: 48,
    status: PRODUCT_STATUS.APPROVED,
    submittedBy: "Ankit",
    userId: "user_snippetHub",
    organizationId: null,
    approvedAt: new Date(),
  },
];
